In [113]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [114]:
df=pd.read_csv('C:/a/run/netflix_titles.csv')
df.drop(['show_id','date_added','rating','duration','listed_in','description'], axis=1, inplace=True)

In [115]:
# 콘텐츠 기반 필터링 
# 예전에 봤던 영화의 특징(장르, 감독, 배우)을 분석
# 유저 프로필과 아이템 프로필 벡터로 만들어 두 벡터가 얼마나 비슷한지 코사인 유사도로 계산한다.

In [116]:
df=df[df['type']=='Movie']

In [117]:
# 결측치 제거
df.isna().sum()
df.dropna(inplace=True)

In [118]:
df.isna().sum()

type            0
title           0
director        0
cast            0
country         0
release_year    0
dtype: int64

In [119]:
# 데이터 300개만 샘플링 (전체 5000여개 중 무작위로 300개만 뽑음)
df=df.sample(n=300, random_state=1)

In [120]:
print(df['release_year'].min())
print(df['release_year'].max())

1967
2021

In [121]:
df['category']=pd.cut(df['release_year'], bins=[1967, 1982, 1997, 2021], labels=['antique','modern','current'])

In [122]:
df.drop('release_year', axis=1, inplace=True)

In [123]:
df

       type                          title  ...                                            country category
2636  Movie       The International Player  ...                                              Egypt  current
4515  Movie                     Kuntilanak  ...                                          Indonesia  current
819   Movie         The Outlaw Josey Wales  ...                                      United States  antique
7035  Movie                           I Am  ...                                       India, Japan  current
6654  Movie                            Dum  ...                                              India  current
...     ...                            ...  ...                                                ...      ...
4830  Movie                  The last hour  ...                                        Chile, Peru  current
7169  Movie                        Karzzzz  ...                                              India  current
8456  Movie         The Pirates of Somalia  ...  Somalia, Kenya, Sudan, South Africa, United St...  current
7843  Movie                  Red Christmas  ...                                          Australia  current
3990  Movie  The Amazing Praybeyt Benjamin  ...                                        Philippines  current

[300 rows x 6 columns]

In [124]:
director1=df['director'].unique()
cast1=df['cast'].unique()
country1=df['country'].unique()
category1=df['category'].unique()

In [125]:
# itemprofile/userprofile

# 제목만 선택해서 데이터프레임형태로 출력 - 원본 df 복사본을 만듬
item_profile=df[['title']].copy()
item_profile

                              title
2636       The International Player
4515                     Kuntilanak
819          The Outlaw Josey Wales
7035                           I Am
6654                            Dum
...                             ...
4830                  The last hour
7169                        Karzzzz
8456         The Pirates of Somalia
7843                  Red Christmas
3990  The Amazing Praybeyt Benjamin

[300 rows x 1 columns]

In [112]:
# df=pd.DataFrame({'score':[60,100,97,93]})
# df['result']=df['score'].apply(lambda x: '합격' if x>70 else '불합격')
# df

   score result
0     60    불합격
1    100     합격
2     97     합격
3     93     합격

In [129]:
# 전체 감독 중에 내가 확인하려는 특정 감독이 해당 영화의 감독 목록에 들어 있는가?? 들어 있으면 1, 아니면 0
for i in director1:
    item_profile[f'director {i}']=df['director'].apply(lambda x: 1 if i in x else 0)

for i in cast1:
    item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)

for i in country1:
    item_profile[f'country {i}']=df['country'].apply(lambda x: 1 if i in x else 0)

for i in category1:
    item_profile[f'category {i}']=df['category'].apply(lambda x: 1 if i in x else 0)

C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)
C:\Users\hi\AppData\Local\Temp\ipykernel_15904\202172745.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  item_profile[f'cast {i}']=df['cast'].apply(lambda x: 1 if i in x else 0)

TypeError: argument of type 'float' is not iterable

In [130]:
item_profile

                              title  ...  cast Vice Ganda, Bimby Aquino-Yap, Alex Gonzaga, Tom Rodriguez
2636       The International Player  ...                                                  0
4515                     Kuntilanak  ...                                                  0
819          The Outlaw Josey Wales  ...                                                  0
7035                           I Am  ...                                                  0
6654                            Dum  ...                                                  0
...                             ...  ...                                                ...
4830                  The last hour  ...                                                  0
7169                        Karzzzz  ...                                                  0
8456         The Pirates of Somalia  ...                                                  0
7843                  Red Christmas  ...                                                  0
3990  The Amazing Praybeyt Benjamin  ...                                                  1

[300 rows x 969 columns]

In [131]:
# 결측지 0으로 채우기 -> 코사인 유사도로 연산시 결측값 있으면 에러일으킴
item_profile.fillna(0, inplace=True)

                              title  ...  cast Vice Ganda, Bimby Aquino-Yap, Alex Gonzaga, Tom Rodriguez
2636       The International Player  ...                                                  0
4515                     Kuntilanak  ...                                                  0
819          The Outlaw Josey Wales  ...                                                  0
7035                           I Am  ...                                                  0
6654                            Dum  ...                                                  0
...                             ...  ...                                                ...
4830                  The last hour  ...                                                  0
7169                        Karzzzz  ...                                                  0
8456         The Pirates of Somalia  ...                                                  0
7843                  Red Christmas  ...                                                  0
3990  The Amazing Praybeyt Benjamin  ...                                                  1

[300 rows x 969 columns]

In [134]:
# 기존의 인덱스는 버리지 않고, 인덱스 0부터 시작
item_profile.reset_index(drop=True, inplace=True)
print(item_profile)

                             title  ...  cast Vice Ganda, Bimby Aquino-Yap, Alex Gonzaga, Tom Rodriguez
0         The International Player  ...                                                  0
1                       Kuntilanak  ...                                                  0
2           The Outlaw Josey Wales  ...                                                  0
3                             I Am  ...                                                  0
4                              Dum  ...                                                  0
..                             ...  ...                                                ...
295                  The last hour  ...                                                  0
296                        Karzzzz  ...                                                  0
297         The Pirates of Somalia  ...                                                  0
298                  Red Christmas  ...                                                  0
299  The Amazing Praybeyt Benjamin  ...                                                  1

[300 rows x 969 columns]

In [135]:
item_profile

                             title  ...  cast Vice Ganda, Bimby Aquino-Yap, Alex Gonzaga, Tom Rodriguez
0         The International Player  ...                                                  0
1                       Kuntilanak  ...                                                  0
2           The Outlaw Josey Wales  ...                                                  0
3                             I Am  ...                                                  0
4                              Dum  ...                                                  0
..                             ...  ...                                                ...
295                  The last hour  ...                                                  0
296                        Karzzzz  ...                                                  0
297         The Pirates of Somalia  ...                                                  0
298                  Red Christmas  ...                                                  0
299  The Amazing Praybeyt Benjamin  ...                                                  1

[300 rows x 969 columns]

In [165]:
# user profile
users_num=10

movies_num=300

# 10행 300열짜리 0/1 matrix형태
# 0~1중에서 랜덤하게 수를 뽑아 10행 300열의 행렬만듬 (0: 해당영화보지않음 1: 해당영화 시청함)
# 시청기록데이터가 없으므로 랜덤하게(0~1) 데이터 설정함
users_movie=np.random.randint(2, size=(users_num, movies_num))
users_movie=pd.DataFrame(users_movie, columns=item_profile['title'])
users_movie

title  The International Player  Kuntilanak  ...  Red Christmas  The Amazing Praybeyt Benjamin
0                             0           1  ...              0                              0
1                             0           0  ...              0                              0
2                             0           1  ...              1                              0
3                             0           1  ...              1                              0
4                             0           1  ...              0                              1
5                             1           0  ...              1                              1
6                             0           0  ...              1                              0
7                             0           0  ...              1                              0
8                             1           0  ...              1                              1
9                             0           1  ...              0                              1

[10 rows x 300 columns]

In [166]:
# 영화의 정보들(영화속성) + 유저의 시청기록 => 행렬 곱 (dot product)
# 유저 취향 벡터 뽑으려고
def user_profile(item_profile, users_movie):
    movie_columns=item_profile.columns.drop('title')
    # 유저의 수만큼 0으로 채움(비어있게 만듬- 초기화)
    # 타입문제로 0.0
    user_profiles=pd.DataFrame(0.0, index=range(len(users_movie)), columns=movie_columns)

    # 시청한 영화 골라내기
    for user_id in range(len(users_movie)):
        w_movies = users_movie.iloc[user_id] == 1 #시청기록 중 숫자가 1인것만 true로 표시됨
        w_titles = users_movie.columns[w_movies] #시청한 영화제목만 뽑아온다

        # item profile에서 유저가 시청한 영화만 뽑아온다(시청한 영화에 대한 정보들이 담겨져있다)
        w_profiles = item_profile[item_profile['title'].isin(w_titles)]

        # 시청한 영화가 없는 경우
        if w_profiles.empty:
            user_profile1 = pd.Series(0, index=movie_columns)
        # 영화를 봤으면 평균계산(영화특징들)
        else:
            user_profile1 = w_profiles[movie_columns].mean()
            user_profile1 = user_profile1.fillna(0)
            
        user_profiles.iloc[user_id] = user_profile1
    return user_profiles.fillna(0)

user1=user_profile(item_profile, users_movie)
user1

   director Ahmed Medhat  ...  cast Vice Ganda, Bimby Aquino-Yap, Alex Gonzaga, Tom Rodriguez
0               0.000000  ...                                           0.000000
1               0.000000  ...                                           0.000000
2               0.000000  ...                                           0.000000
3               0.000000  ...                                           0.000000
4               0.000000  ...                                           0.007042
5               0.006410  ...                                           0.006410
6               0.000000  ...                                           0.000000
7               0.000000  ...                                           0.000000
8               0.006993  ...                                           0.006993
9               0.000000  ...                                           0.006452

[10 rows x 968 columns]

In [167]:
# 코사인 유사도 계산
from sklearn.metrics.pairwise import cosine_similarity

In [186]:
# 유저의 취향을 알았으니, 모든 영화와 대조해서 가장 취향에 맞는 5개의 영화를 골라줌
def movie_recommend(item_profile, user_profiles, top_n=5):
    recommend={}

    movie_columns=item_profile.columns.drop('title')
    item_features=item_profile[movie_columns].fillna(0)

    for user_id in range(len(user_profiles)):
        # 1차원 -> 2차원으로 만듬(1행은 고정 열은 자동으로 맞춰줌)
        user_profile=user_profiles.iloc[user_id].values.reshape(1,-1)
        user_profile=np.nan_to_num(user_profile)

        # 유저의 취향벡터와 300개 영화벡터 사이의 각도를 잰다 (0~1)
        similarity=cosine_similarity(user_profile, item_features)

        # 점수가 낮은 순서대로 인덱스 번호 준 다음에 뒤에서 5개를 자른다.
        # 순서를 뒤집어서 가장 높은 점수가 맨 앞으로 오게 만든다.
        top_similarity=np.argsort(similarity[0][-top_n:][::-1])

        # 추천영화 담을 빈 리스트
        recom_movies=[]

        for i in top_similarity:
            # 유사도가 높은 5개를 반복 순회하면서 해당 인덱스의 영화제목을 뽑는다.
            movie_title=item_profile.iloc[i]['title']
            similarity_score=similarity[0][i]
            recom_movies.append({
                'title':movie_title,
                'similarity_score':similarity_score})
        # 딕셔너리에 저장 dic['age']=20 dic{'age':20}
        recommend[f'{user_id}']=recom_movies

    return recommend

recom=movie_recommend(item_profile, user_profiles)
recom

{'0': [{'title': 'The International Player',
   'similarity_score': np.float64(0.0)},
  {'title': 'Kuntilanak', 'similarity_score': np.float64(0.0)},
  {'title': 'The Outlaw Josey Wales', 'similarity_score': np.float64(0.0)},
  {'title': 'I Am', 'similarity_score': np.float64(0.0)},
  {'title': 'Dum', 'similarity_score': np.float64(0.0)}],
 '1': [{'title': 'The International Player',
   'similarity_score': np.float64(0.0)},
  {'title': 'Kuntilanak', 'similarity_score': np.float64(0.0)},
  {'title': 'The Outlaw Josey Wales', 'similarity_score': np.float64(0.0)},
  {'title': 'I Am', 'similarity_score': np.float64(0.0)},
  {'title': 'Dum', 'similarity_score': np.float64(0.0)}],
 '2': [{'title': 'The International Player',
   'similarity_score': np.float64(0.0)},
  {'title': 'Kuntilanak', 'similarity_score': np.float64(0.0)},
  {'title': 'The Outlaw Josey Wales', 'similarity_score': np.float64(0.0)},
  {'title': 'I Am', 'similarity_score': np.float64(0.0)},
  {'title': 'Dum', 'similarity_score': np.float64(0.0)}],
 '3': [{'title': 'The International Player',
   'similarity_score': np.float64(0.0)},
  {'title': 'Kuntilanak', 'similarity_score': np.float64(0.0)},
  {'title': 'The Outlaw Josey Wales', 'similarity_score': np.float64(0.0)},
  {'title': 'I Am', 'similarity_score': np.float64(0.0)},
  {'title': 'Dum', 'similarity_score': np.float64(0.0)}],
 '4': [{'title': 'The International Player',
   'similarity_score': np.float64(0.0)},
  {'title': 'Kuntilanak', 'similarity_score': np.float64(0.0)},
  {'title': 'The Outlaw Josey Wales', 'similarity_score': np.float64(0.0)},
  {'title': 'I Am', 'similarity_score': np.float64(0.0)},
  {'title': 'Dum', 'similarity_score': np.float64(0.0)}],
 '5': [{'title': 'The International Player',
   'similarity_score': np.float64(0.0)},
  {'title': 'Kuntilanak', 'similarity_score': np.float64(0.0)},
  {'title': 'The Outlaw Josey Wales', 'similarity_score': np.float64(0.0)},
  {'title': 'I Am', 'similarity_score': np.float64(0.0)},
  {'title': 'Dum', 'similarity_score': np.float64(0.0)}],
 '6': [{'title': 'The International Player',
   'similarity_score': np.float64(0.0)},
  {'title': 'Kuntilanak', 'similarity_score': np.float64(0.0)},
  {'title': 'The Outlaw Josey Wales', 'similarity_score': np.float64(0.0)},
  {'title': 'I Am', 'similarity_score': np.float64(0.0)},
  {'title': 'Dum', 'similarity_score': np.float64(0.0)}],
 '7': [{'title': 'The International Player',
   'similarity_score': np.float64(0.0)},
  {'title': 'Kuntilanak', 'similarity_score': np.float64(0.0)},
  {'title': 'The Outlaw Josey Wales', 'similarity_score': np.float64(0.0)},
  {'title': 'I Am', 'similarity_score': np.float64(0.0)},
  {'title': 'Dum', 'similarity_score': np.float64(0.0)}],
 '8': [{'title': 'The International Player',
   'similarity_score': np.float64(0.0)},
  {'title': 'Kuntilanak', 'similarity_score': np.float64(0.0)},
  {'title': 'The Outlaw Josey Wales', 'similarity_score': np.float64(0.0)},
  {'title': 'I Am', 'similarity_score': np.float64(0.0)},
  {'title': 'Dum', 'similarity_score': np.float64(0.0)}],
 '9': [{'title': 'Dum', 'similarity_score': np.float64(0.18671988585632254)},
  {'title': 'Kuntilanak',
   'similarity_score': np.float64(0.042162554870782507)},
  {'title': 'The International Player',
   'similarity_score': np.float64(0.0301161106219875)},
  {'title': 'I Am', 'similarity_score': np.float64(0.1868817302880742)},
  {'title': 'The Outlaw Josey Wales',
   'similarity_score': np.float64(0.40957910445903006)}]}

In [175]:
#  #시청한 영화 골라내기
# movie_columns=item_profile.columns.drop('title')

# for user_id in range(10):
#     user_profiles=pd.DataFrame(0.0, index=range(len(users_movie)), columns=movie_columns)
#     w_movies = users_movie.iloc[user_id] == 1 #시청기록 중 숫자가 1인것만 true로 표시됨
#     w_titles = users_movie.columns[w_movies] #시청한 영화제목만 뽑아온다

#         #item profile에서 유저가 시청한 영화만 뽑아온다(시청한 영화에 대한 정보들이 담겨져있다)
#     w_profiles = item_profile[item_profile['title'].isin(w_titles)]

#     user_profile1 = w_profiles[movie_columns].mean()
#     user_profile1 = user_profile1.fillna(0)
            
#     user_profiles.iloc[user_id] = user_profile1
#     print(user_profiles.iloc[user_id].values.reshape(1,-1))

In [176]:
top_similarity=np.argsort(([4,5,6])[-2:][::-1])
top_similarity

array([1, 0])